apiVersion: v1
kind: Service
metadata:
  name: secure-devex22
  labels:
    type: microservice
spec:
  selector:
    app: secure-devex22
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
    - name: management
      protocol: TCP
      port: 8081
      targetPort: management
