apiVersion: v1
kind: Service
metadata:
  labels:
    type: zap-gui
  name: zap-gui
spec:
  ports:
    - name: proxy
      port: 8090
      targetPort: 8090
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    type: zap-gui
