# This workflow uses actions that are not certified by GitHub.

name: OWASP Dependency Check

on:
  workflow_dispatch:
  # schedule:
  #  - cron: '26 22 * * 2'

permissions:
  contents: read

jobs:
  dependency-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Dependency Check
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: dependencyCheckAnalyze
